"""empty message

Revision ID: 082a1f61f6c1
Revises: 6c03c5ef3fa6
Create Date: 2023-10-17 16:30:28.249187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082a1f61f6c1'
down_revision = '6c03c5ef3fa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.alter_column('parking',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.alter_column('parking',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
