"""empty message

Revision ID: 9d27abc0afd2
Revises: f27cf2e6b2d2
Create Date: 2023-11-07 14:45:34.649540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d27abc0afd2'
down_revision = 'f27cf2e6b2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.Boolean(), nullable=True))
        batch_op.drop_column('availabity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availabity', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('availability')

    # ### end Alembic commands ###
