"""empty message

Revision ID: f27cf2e6b2d2
Revises: 796b031aacfa
Create Date: 2023-10-28 20:46:22.295536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27cf2e6b2d2'
down_revision = '796b031aacfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startTime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('endTime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('totalCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('totalCost')
        batch_op.drop_column('endTime')
        batch_op.drop_column('startTime')

    # ### end Alembic commands ###
